### ISSUE TITLE
장보기 상품 썸네일 하트 아이콘 좋아요 수 반영 안됨

### ISSUE THREAD

**Issue by hyooyh8910** [ad-earth/FE-client#167]

**Comment by hyooyh8910** [comment]
로그인하면 됩니당! 로그아웃시 클릭하면 알러트를 띄울게요!

**Comment by sol-pine** [comment]
default alert message 대신에 공통 toast ui 활용해주세요
현재 작업하고 있는 개발 끝나면 작업한 toast ui PR 하겠습니다! 감사합니다😊

**Comment by hyooyh8910** [comment]
넵 알겠습니다~ pr 머지되면 toast ui로 반영할게요! 감사합니다😀
