### ISSUE TITLE
react-router-dom error

### ISSUE THREAD

**Issue by whl5105** [ad-earth/FE-client#2]
원인 : Uncaught Error: useRoutes() may be used only in the context of a <Router> component.
<img width="606" alt="image" src="https://user-images.githubusercontent.com/73993670/186357843-dd3c0e5f-4417-4dc5-bfff-3dfda10cd62c.png">

해결 : import {BrowserRouter as Router } from "react-router-dom"; 선언 후 <Router></Router> 추가 
 useRoutes()는 Routes 감싸야하는 BrowserRouter as Router 가 필요해 보입니다.

**Comment by sol-pine** [comment]
index.tsx 에 BrowserRouter 추가하였습니다 😊
